"use client";
import Image from "next/image";
import Link from "next/link";
import { useParams } from "next/navigation";
import { BadgeCheck, MapPin } from "lucide-react";
import useConvexFreelancerDetail from "@/hook/useConvexFreelancerDetail";
import SavedItemButton from "@/components/ui/SavedItemButton";
import ReportButton from "@/components/trust/ReportButton";
export default function LocalProfessionalProfile() {
  const { id } = useParams();
  const profile = useConvexFreelancerDetail(id, "local");
  if (profile === undefined) return <main className="container py-12" role="status">Loading local professional…</main>;
  if (!profile) return <main className="container py-12"><h1 className="text-3xl font-semibold">Professional not available</h1><p className="my-4">This local profile is not public or no longer exists.</p><Link href="/local/craftsmen">Browse local professionals</Link></main>;
  const location = [profile.locationCity, profile.locationCountry].filter(Boolean).join(", ");
  return <main className="container py-10"><nav aria-label="Breadcrumb" className="mb-6 text-sm"><Link href="/local">Local</Link> / <Link href="/local/craftsmen">Professionals</Link> / {profile.displayName}</nav><div className="grid items-start gap-7 lg:grid-cols-[minmax(0,1fr)_320px]"><section className="rounded-2xl border bg-white p-7"><div className="flex flex-wrap items-center gap-5"><Image src={profile.avatarUrl || "/images/team/default-avatar.svg"} width={100} height={100} alt={profile.displayName} className="rounded-full" /><div><h1 className="text-3xl font-semibold">{profile.displayName}</h1><p className="mt-2">{profile.tagline || "Local professional"}</p>{profile.isVerified ? <p className="mt-2 flex items-center gap-1 text-sm"><BadgeCheck size={16} />Verified profile</p> : null}</div></div><h2 className="mb-3 mt-8 text-xl font-semibold">About this professional</h2><p className="whitespace-pre-line">{profile.bio || "An introduction has not been added yet."}</p><h2 className="mb-3 mt-8 text-xl font-semibold">Trades and skills</h2>{profile.skills.length === 0 && <p>No trades or skills have been published yet.</p>}<div className="flex flex-wrap gap-2">{profile.skills.map((skill) => <span key={skill} className="rounded-lg bg-slate-50 px-3 py-2">{skill}</span>)}</div>{profile.languages.length ? <p className="mt-6">Languages: {profile.languages.join(", ")}</p> : null}</section><aside className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Service area</h2><p className="my-3 flex items-center gap-2"><MapPin size={18} />{location || "Confirm the service area"}</p>{profile.serviceRadiusKm != null ? <p>Up to {profile.serviceRadiusKm} km from the listed area.</p> : null}<p className="my-5 text-xl font-semibold">{profile.hourlyRate != null ? "€" + profile.hourlyRate + " / hour" : "Rate on request"}</p><p className="mb-5">{profile.isAvailable ? "Accepting new requests. Confirm dates and scope before work begins." : "Not currently accepting new work."}</p><Link className="btn btn--primary w-full" href="/local/request-quote">Create a local quote request</Link><p className="my-3 text-sm text-[var(--text-secondary)]">A request describes your job. It does not book this professional automatically.</p><SavedItemButton itemType="freelancer" itemId={profile._id} title={profile.displayName} image={profile.avatarUrl} href={"/local/craftsman/" + (profile.slug || profile._id)} showLabel className="btn btn--secondary w-full" /><ReportButton targetType="freelancer" targetId={profile._id} targetLabel={profile.displayName} /></aside></div></main>;
}
