// Editorial recovery from the pre-redesign URL inventory. Prices checked 2026-09-08.
// English resources keep the existing /en/ -> /resources/ canonical migration.
const section = (title, body, items = [], source, links = []) => ({ title, body, items, source, links });
const link = (path, label) => ({ path, label });
const upwork = ['Upwork: freelancer service fees', 'https://support.upwork.com/hc/en-us/articles/211062538-Learn-about-the-Freelancer-Service-Fee'];
const fiverr = ['Fiverr: understanding your earnings', 'https://help.fiverr.com/hc/en-us/articles/9234443621137-Your-earnings-page'];
const toptal = ['Toptal: client FAQ', 'https://www.toptal.com/faq'];
const choice = '/en/guides/platform-selectie/beste-freelance-platform-kiezen';
const review = '/en/guides/platform-reviews/fiverr-pros-cons-deep-dive';
const portfolio = '/resources/building-portfolio-that-converts';
const profile = '/resources/optimizing-freelance-profile-maximum-visibility';
const invoice = '/resources/freelance-invoice-generator';
const invoicing = '/resources/freelance-invoicing-guide';
const pricing = '/resources/upwork-pricing';
const writers = '/resources/best-platform-writers';
function guide(slug, title, description, intro, example, sections, faq, related, extra = {}) {
  return { slug, path: `/resources/${slug}`, type: 'guide', keyword: title, skill: '', title, description, intro, example, sections, faq, related, ...extra };
}

export const recoveryPages = [
  guide('upwork-review', 'Upwork Review: Scope, Proposals and Project Fit', 'Evaluate Upwork for freelance work or hiring. Review the proposal process, project scope, fees and checks to make before accepting an engagement.',
    'Upwork connects clients and freelancers through a marketplace. Whether it suits you depends on the projects available, the evidence you can assess and the time needed to agree on and manage the work. This is a practical assessment, not a claim based on our own paid hiring experience.',
    ['Start with a specific project or service.', 'Review the terms of the actual contract.', 'Include selection and coordination in your time budget.'], [
      section('How the marketplace process fits your project', 'For a proposal-led project, the client describes the work and evaluates candidates. The useful question is whether the brief contains enough detail to make offers comparable. If key requirements are unknown, scope a discovery step before committing to a large implementation.', [], ['Upwork: how the freelancer process works', 'https://www.upwork.com/i/how-it-works/freelancer/'], [link('/resources/how-to-hire-a-freelancer', 'Prepare a hiring brief')]),
      section('For clients: define the first reviewable milestone', 'Specify a deliverable, the required inputs and how you will assess it. Ask candidates about similar work and their own contribution. A high-level profile claim does not establish suitability for your project. Name the person who consolidates feedback and approves changes.'),
      section('For freelancers: qualify before applying', 'Look for work that matches your skills, availability and delivery process. Ask focused questions about unclear scope. Include proposal effort, meetings and revisions when assessing the economics; the posted budget alone cannot tell you whether a project is sustainable.', [], undefined, [link('/resources/freelance-proposal-template', 'Write a proposal with clear scope')]),
      section('Fees do not automatically fall as a client spends more', 'Do not rely on the old sliding-tier fee description in earlier reviews. Check the current contract-specific fee and any applicable programme terms. Our pricing guide separates the service fee from acquisition costs and explains net-earnings calculations.', [], undefined, [link(pricing, 'Read the current Upwork pricing guide')]),
      section('Read payment and dispute conditions before starting', 'Confirm the applicable contract type and what records or steps are required under its terms. Keep scope, approvals and delivery evidence together. Payment tools do not remove the need for a clear agreement, and they should not be described as an unconditional guarantee.', [], ['Upwork: legal terms', 'https://www.upwork.com/legal']),
      section('When to compare another channel', 'For a defined package, compare a Gig-style offer; for assisted specialist selection, compare a matching service. Use the same brief and review the actual candidates rather than treating a platform’s reputation as the result.', [], undefined, [link('/resources/fiverr-vs-upwork', 'Compare Upwork with Fiverr'), link('/resources/toptal-vs-upwork', 'Compare Upwork with Toptal')])
    ], [['Does a long client relationship guarantee a lower fee?', 'Do not assume that from an old review. Check the current fee rules and the specific contract.'], ['Does this review include a firsthand hiring test?', 'No. It combines the provider’s published information with a practical evaluation checklist. It does not assign an invented review score.']], [pricing, choice], { path: '/platforms/upwork', reviewed: '2026-09-09' }),
  guide('fiverr-vs-upwork', 'Upwork vs Fiverr: Compare Fees, Scope and Hiring', 'Compare Upwork and Fiverr using the same project brief. Understand seller fees, package scope, proposals and the work needed to assess candidates.',
    'Use Upwork and Fiverr to compare ways of buying and selling work, not assumed levels of talent. A clearly packaged deliverable and an open-ended project need different conversations before the price makes sense.',
    ['Compare equivalent deliverables and revisions.', 'Separate buyer costs from freelancer earnings.', 'Review the actual candidate and agreement.'], [
      section('The core difference: proposals and packages', 'A common Upwork workflow starts with a client’s brief and freelancer proposals. A common Fiverr workflow starts with a seller’s Gig package. Both require scope clarification: a package does not answer every project question, and a proposal is not automatically a complete specification. Choose the process that lets you agree on the work before committing.', [], undefined, [link(review, 'Look more closely at the Fiverr Gig model')]),
      section('Compare fees on the same side of the transaction', 'For freelancer earnings, consult the current Upwork contract fee and Fiverr earnings rules. Do not compare an Upwork client checkout total with a Fiverr seller’s take-home amount. Optional features, currency costs and taxes can change the economics. Confirm the applicable figures before accepting a contract or placing an order.', [], undefined, [link(pricing, 'Use the Upwork fee examples')]),
      section('For clients: inspect deliverables before ordering', 'Give each candidate the same page list, asset list or other scope. Ask what is included, who supplies inputs and how feedback is handled. Check a work sample relevant to your project and ask about the person’s contribution. A package’s delivery time is not a substitute for agreeing when you will supply content and approve work.'),
      section('For freelancers: include acquisition and revision time', 'On a proposal-led channel, record the time and costs of applications. On a package-led channel, record enquiry handling, clarifications and revisions. Neither route produces work passively just because a profile exists. Compare qualified conversations and sustainable delivery margins over a defined test period.'),
      section('Review payment and dispute terms directly', 'Check the requirements of the specific contract type, how milestones or deliveries are accepted and what evidence you must keep. A platform’s payment features do not guarantee that every disagreement ends in your favour. Follow the current platform terms and keep the agreed scope, approvals and delivery record together.', [], ['Upwork legal terms', 'https://www.upwork.com/legal']),
      section('A practical comparison exercise', 'Imagine a five-page website with supplied copy, two design review rounds and an editable handover. Ask how each candidate handles missing copy, additional pages and a change of direction. Compare their answers and total scope, then the price. This exposes differences a platform-wide star rating would miss.', [], undefined, [link('/services/webdesign', 'Prepare a comparable web design brief'), link(choice, 'Use the platform choice scorecard')])
    ], [['Which platform has better freelancers?', 'Assess the candidates available for your project. Platform-wide assumptions about quality or seniority do not establish individual fit.'], ['Is Fiverr passive income for sellers?', 'Creating a Gig does not guarantee enquiries or orders. Sellers still need to define, communicate and deliver the work.']], [review, pricing, choice], { reviewed: '2026-09-09' }),

  guide('toptal-for-beginners', 'Toptal for Beginners: Prepare for the Application Process', 'Prepare for Toptal with relevant experience, portfolio evidence and a realistic view of screening and matching. Check the official talent requirements.',
    'If you are new to Toptal, start by checking whether your experience matches the current talent requirements. Prepare examples you can explain in detail and plan time for screening. Joining a network and securing a suitable engagement are separate steps.',
    ['Check the current requirements for your specialism.', 'Prepare evidence of your own contribution.', 'Treat acceptance and project availability separately.'], [
      section('Is Toptal suitable for a complete beginner?', 'Toptal’s talent FAQ describes successful applicants as typically having at least two to three years of relevant experience. Someone new to the platform may qualify; someone new to the profession may need more practical experience first. Check the current requirements for your role rather than treating a generic checklist as a promise of eligibility.', [], ['Toptal: official talent FAQ', 'https://www.toptal.com/freelance-jobs/faq']),
      section('Prepare projects you can discuss', 'Select work that shows the skills you want to use on future engagements. Explain the initial problem, your responsibility, the constraints and the decisions you made. Have enough detail to answer questions about trade-offs. Use only material you are entitled to share and remove private client data.', [], undefined, [link(portfolio, 'Prepare portfolio case studies for review')]),
      section('Understand screening before allocating your time', 'The provider describes a multi-stage screening process covering expertise, professionalism and communication, typically taking a few weeks. Read the instructions you receive for the actual assessment rather than relying on a universal sequence from an old review. Reserve preparation time without assuming a specific acceptance date.'),
      section('Submit accurate experience and availability', 'Use the official application route, keep dates and roles consistent with your portfolio and describe availability honestly. If you need clarification or an accommodation, use the contact options in the official talent FAQ. Do not pay an unofficial intermediary claiming to guarantee admission.'),
      section('Plan for matching after acceptance', 'A profile should explain your specialism and current availability. Evaluate each proposed engagement for scope, collaboration hours and responsibilities. The provider notes that work volume depends on client requirements and availability, so do not budget on the assumption of immediate or uninterrupted work.', [], undefined, [link(profile, 'Make your freelance profile specific')]),
      section('If your application is not accepted', 'Use any feedback you receive to identify practical gaps, such as project depth or communicating technical decisions. Toptal says a waiting period typically applies between attempts; check your own instructions before reapplying. Meanwhile, build relevant work and consider other channels that fit your present offer.', [], undefined, [link(choice, 'Compare alternative freelance channels'), link('/resources/what-is-toptal', 'Understand the client-side Toptal model')])
    ], [['Does joining guarantee a steady income?', 'No. Keep acceptance, availability and a signed engagement separate in your planning.'], ['Can I use an unofficial service to guarantee admission?', 'Do not rely on that claim. Apply through the official process and follow the provider’s own instructions.']], ['/resources/what-is-toptal', portfolio], { reviewed: '2026-09-09' }),

  guide('freelancer-vs-guru', 'Freelancer vs Guru: Fees, Project Fit and Working Terms', 'Compare Freelancer.com and Guru by project fees, membership costs and working process. Use actual briefs rather than assumptions about platform size.',
    'Compare Freelancer.com and Guru against the work you want to do and the terms of a real project. Registered-user totals cannot tell you how much relevant demand or competition you will face in your niche.',
    ['Look for relevant briefs, not headline user counts.', 'Include minimum fees and membership costs.', 'Read payment terms for the actual project.'], [
      section('Freelancer.com: account for the minimum fee', 'Freelancer.com currently lists its standard freelancer fixed-price fee as 10% or US$5, whichever is greater, and its standard hourly fee as 10%. For an illustrative US$20 fixed-price project, the US$5 minimum is 25% of the project value. Check special programmes and other applicable charges separately.', [], ['Freelancer.com: official fees and charges', 'https://www.freelancer.com/feesandcharges']),
      section('Guru: compare membership and job fees together', 'Guru’s freelancer pricing page lists job fees from 9% down to 5% across its membership levels. A lower job fee is not automatically cheaper once a paid membership is included. Compare the fee saving at your expected volume with the subscription cost and renewal terms before choosing a plan.', [], ['Guru: official freelancer pricing', 'https://www.guru.com/pricing-freelancer/']),
      section('Use a break-even calculation', 'For an optional membership, divide its incremental cost by the percentage-point fee saving to estimate the eligible work volume needed to cover that cost. For example, a hypothetical US$20 subscription saving two percentage points needs US$1,000 of eligible billings to break even. This illustrates the method; it is not a quote for either provider.'),
      section('Inspect actual project demand', 'Review a small set of current briefs in your skill and price range. Note the scope quality, client requirements and effort needed to respond. A smaller platform does not prove lower competition, and a larger one does not prove you will receive more suitable work. Use your own test results to decide.'),
      section('Payment protection is contractual', 'A company’s stock-market listing is not a payment guarantee for your project. Check the provider’s payment system, funding requirements, acceptance process and dispute terms. Keep approvals and deliverables documented. Avoid taking a provider’s general security messaging as proof that every transaction is protected.'),
      section('Test one channel with a defined offer', 'Keep the offer, portfolio and test period consistent so you can learn from the result. Count qualified conversations, paid work and time spent, not just applications. Improve a weak brief or sample before adding more platforms.', [], undefined, [link(choice, 'Use a platform selection scorecard'), link('/resources/freelance-proposal-template', 'Define your proposal scope')])
    ], [['Does Guru necessarily have less competition?', 'No. Platform size is not enough evidence; assess the specific work and candidates in your niche.'], ['Are membership costs included in the project fee?', 'Read the current plan terms. Compare recurring charges, project fees and any other costs separately.']], [pricing, choice], { reviewed: '2026-09-09' }),

  guide('99designs-pricing', '99designs Pricing: Contest Packages and 1-to-1 Projects', 'Compare 99designs contest packages and direct design projects. Check category-specific prices, platform fees, add-ons and terms before committing.',
    '99designs offers different ways to commission design. A contest package and a project with one designer have different cost structures. Start with your deliverables and category, then compare the current quote and terms.',
    ['Select the right design category before comparing prices.', 'Separate project fees, platform fees and optional costs.', 'Check terms before advancing a contest or accepting a quote.'], [
      section('Contest prices depend on the selected category', 'When checked on 9 September 2026, the official US-dollar logo-design page showed Bronze US$249, Silver US$399, Gold US$799 and Platinum US$1,050, excluding sales tax. These are a dated snapshot for that category and currency, not a universal price list for every design service. Recheck the category and checkout before buying.', [], ['99designs: current category pricing', 'https://99designs.com/pricing']),
      section('Compare package inclusions rather than concept counts alone', 'Review the package’s deliverables, designer eligibility and support. An approximate number of concepts is not a guarantee that one will fit your brief. Make the brief concrete enough for designers to understand your audience, intended use and constraints. Identify the decision-maker before reviewing submissions.', [], undefined, [link('/services/graphic-design', 'Prepare a graphic design brief')]),
      section('For a 1-to-1 project, start with the agreed scope', 'The 99designs help centre states that clients pay a 5% platform fee for 1-to-1 Projects and designers pay a separate fee based on their level. An illustrative US$2,000 design quote plus that 5% client fee totals US$2,100 before other applicable costs or taxes. Confirm the final quote and transaction details directly.', [], ['99designs: platform fee explanation', 'https://support.99designs.com/hc/en-us/articles/360022206031-What-is-a-platform-fee']),
      section('Read refund and ownership conditions in context', 'Check the current terms for your chosen project type before committing or moving a contest forward. Do not assume that a headline money-back message applies to every stage, add-on or situation. Confirm what files and rights are included in the final handover and what input you must provide.', [], ['99designs: terms and conditions', 'https://99designs.com/legal/terms-and-conditions']),
      section('Build a complete cost comparison', 'List the base price, optional upgrades, applicable taxes and any further work needed after the initial delivery. Use the same deliverable list when comparing a contest with a direct engagement. A logo file, a brand guide and a complete identity system are different scopes.', ['Required files and export formats.', 'Number and process of feedback rounds.', 'Any optional promotion or privacy features.', 'Follow-up adaptations and handover support.'], undefined, [link('/resources/best-platform-designers', 'Compare channels for design projects')])
    ], [['Are the listed logo prices valid for every design category?', 'No. Check the selected category, currency, current checkout and included scope.'], ['Is a contest always cheaper than a direct project?', 'Compare complete scopes and final costs. Different package and project structures can make headline prices misleading.']], ['/services/graphic-design', '/resources/best-platform-designers'], { reviewed: '2026-09-09' }),

  guide('freelance-invoice-generator', 'Free Freelance Invoice Generator', 'Create a freelance invoice with line items, currency and optional tax. Preview it and print or save as PDF in your browser. No account required.',
    'Create an invoice from your agreed scope, review the totals and save a PDF using your browser’s print dialog. The tool runs in your browser and does not send invoice details to SkillLinkup.',
    ['Enter your business and client details.', 'Add the work, rates and any applicable tax.', 'Review the preview, then print or save as PDF.'], [
      section('Create your invoice', 'Open the generator to enter an invoice number, dates, billing addresses and itemised work. Keep the invoice number consistent with your own records; the tool does not reserve or issue numbers in an accounting system.', [], undefined, [link('/en/tools/invoice-generator', 'Open the free invoice generator')]),
      section('Describe work so the client can approve it', 'Use the same milestone names as the approved proposal. “Homepage design: approved desktop and mobile layouts” is easier to reconcile than “design work”. Use a separate line for each agreed item, with quantity and unit rate. For hourly work, keep the time record that supports the billed quantity.', [], undefined, [link('/resources/freelance-proposal-template', 'Set out deliverables in a freelance proposal')]),
      section('Check tax and payment details', 'The generator applies one tax percentage to the subtotal. It does not decide which tax treatment applies, produce structured e-invoices or handle multiple tax rates. Use suitable accounting software for those cases. Confirm your jurisdiction’s invoice requirements before sending, and add the correct payment reference and due date.', [], undefined, [link(invoicing, 'Check the freelance invoicing workflow')]),
      section('Keep a copy after exporting', 'Previewing or printing an invoice does not send it to the client or record a payment. Save the exported file in your business records, then send it through your usual agreed channel. Unsaved input disappears when you reload or leave the tool. Avoid entering sensitive details on a shared computer.')
    ], [['Is this really free?', 'Yes. You can create and print an invoice without joining the waitlist or creating an account.'], ['Can I download a PDF?', 'Choose Download PDF in the tool. Your invoice downloads directly from your device. Open the PDF if you also want to print it.'], ['Does it calculate my tax obligations?', 'No. You enter the rate. Check local requirements and use an appropriate accounting tool for more complex tax cases.']], [invoicing, '/resources/essential-freelance-tools'], { toolLink: '/en/tools/invoice-generator', skill: 'Freelancing', role: 'freelancer' }),

  guide('building-portfolio-that-converts', 'Build a Freelance Portfolio That Helps Clients Decide', 'Turn freelance work into clear case studies: show your role, decisions, deliverables and evidence. Includes a practical portfolio review checklist.',
    'A useful freelance portfolio answers a buying question: can this person handle a project like mine? Choose relevant work, explain what you personally did and make the next step easy to understand.',
    ['Choose work that resembles the projects you want.', 'Show decisions and deliverables, not only screenshots.', 'Separate measured results from assumptions.'], [
      section('Choose a specific reader', 'Write down the client, project type and constraint you want to work with. A small business commissioning its first website needs different evidence from a product team hiring for an existing design system. Put the closest example first. Remove unrelated work when it makes your offer harder to understand.', [], undefined, [link(choice, 'Choose a freelance platform for your offer')]),
      section('Use a repeatable case-study structure', 'Start with the brief, then explain your role, constraints, approach and final deliverables. Include enough detail to show how you made decisions. A rejected direction can be useful if it explains why the final solution fits the brief. Name collaborators so the reader knows which work is yours.', ['Brief: who needed what, and why?', 'Responsibility: what did you own and what did others contribute?', 'Decision: what trade-off shaped the work?', 'Evidence: what was delivered or measured?']),
      section('Make the evidence honest', 'If you have measured results, state the source, period and relevant limitations. If you do not, show a verifiable deliverable: a completed component library, a published article or a documented handover. Label self-initiated concepts as concepts. Ask permission before sharing client material; redact private information instead of publishing screenshots from internal systems.'),
      section('Give the client an appropriate next step', 'After each case study, explain which similar work you are available for and what you need to estimate it. For example: “For a five-page service website, send your current site, page list and target launch date.” A clear next step is more useful than a claim that you can transform any business.', [], undefined, [link('/services/webdesign', 'What a web design brief should include'), link(profile, 'Carry your portfolio evidence into your profile')])
    ], [['What if I have no paid projects?', 'Create a small, relevant concept project and label it clearly. Explain the brief and decisions without inventing a client, testimonial or commercial result.'], ['How many projects should I show?', 'Start with a few relevant examples that you can explain well. Add another only when it demonstrates a capability your existing work does not.']], [profile, '/resources/freelance-proposal-template']),

  guide('essential-freelance-tools', 'Essential Freelance Tools: Build a Simple Working Setup', 'Choose a practical freelance tool stack for briefs, files, time tracking and invoices. Use a workflow checklist before adding subscriptions.',
    'Start with the work you need to deliver. A useful freelance setup keeps the brief, current files, approvals and payment records easy to find. You do not need a separate subscription for every step.',
    ['One agreed place for the brief and feedback.', 'A clear source of truth for current files.', 'A repeatable way to track work and invoice it.'], [
      section('Map the handoffs first', 'Follow one project from enquiry to payment. Record where the client sends the brief, where you confirm scope, how feedback arrives and where final files go. If you already have a dependable shared document and folder, keep them until a specific problem justifies changing tools.', [], undefined, [link('/resources/freelance-proposal-template', 'Start with a clear proposal template'), link('/resources/ai-tools-for-freelancers', 'Evaluate an AI-assisted workflow')]),
      section('Choose communication and file tools together', 'Check whether the client can access shared material without a paid account, whether permissions are understandable and whether you can export the final work. Give files dates or versions and identify the approved version. Avoid scattering approval across several chats; summarise the decision in the agreed project record.', ['Brief and decisions: one shared document.', 'Deliverables: one clearly named project folder.', 'Feedback: one named approver and one channel.', 'Handover: a file list, access details and ownership check.']),
      section('Track time when it answers a question', 'Time tracking can support hourly billing or show whether a fixed-price project was profitable. Evaluate the export your client or accountant needs before choosing a plan. Test the workflow on a sample project instead of adopting a tool because it has a long feature list.', [], undefined, [link('/resources/best-time-tracking-tools-freelancers', 'Compare time-tracking workflows')]),
      section('Connect delivery to invoicing', 'Record the accepted milestone, invoice number, due date and payment status. Our browser invoice generator can prepare a simple PDF; it does not replace bookkeeping or payment collection. For recurring billing, multiple tax rates or mandatory e-invoicing, evaluate accounting software against those requirements.', [], undefined, [link(invoice, 'Create a simple freelance invoice'), link(invoicing, 'Set up an invoicing process')])
    ], [['Which tools should a beginner buy first?', 'Buy only when your current setup cannot handle a real requirement. Access control, reliable export and client usability are better starting criteria than the number of features.'], ['Should every client use my tools?', 'Agree on a workable process together. Check account costs, access and how the client receives the final records before starting.']], [invoice, '/resources/best-time-tracking-tools-freelancers']),

  guide('freelance-invoicing-guide', 'Freelance Invoicing Guide: From Approved Work to Payment', 'Prepare a clear freelance invoice, check local requirements and keep payment records. Includes a practical send-and-follow-up checklist.',
    'A freelance invoice connects completed work to an agreed payment. Confirm the billing details before you start, describe the work precisely and keep a record of what you sent and when it was paid.',
    ['Confirm who should receive and approve the invoice.', 'Match the invoice to the agreed scope and currency.', 'Keep the invoice and payment record together.'], [
      section('Collect billing details before delivery', 'Ask for the legal billing name, address, accounts-payable contact and any purchase-order reference the client needs. Agree on currency, payment timing and the event that triggers invoicing. A client’s trading name may differ from its billing entity. Resolve that before you send the document.', [], undefined, [link('/resources/freelance-proposal-template', 'Define payment stages in your proposal')]),
      section('Use local requirements, not a universal template', 'Invoice rules depend on where your business operates and its tax status. For example, UK government guidance lists identification, date, description and amount requirements and distinguishes VAT invoices. Treat the official requirements for your own situation as the checklist; a generated PDF alone does not establish compliance.', [], ['UK government: invoice requirements', 'https://www.gov.uk/invoicing-and-taking-payment-from-customers/invoices-what-they-must-include']),
      section('Check Dutch invoice requirements where relevant', 'For a Dutch business, consult the Belastingdienst’s invoice requirements, including applicable exceptions. Do not infer that a zero tax percentage is the right treatment merely because the client is abroad. If the transaction needs special wording, multiple rates or an electronic invoice format, use a workflow that supports those requirements.', [], ['Belastingdienst: factuureisen', 'https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/administratie_bijhouden/facturen_maken/factuureisen/']),
      section('Review, send and reconcile', 'Check names, dates, amounts, currency and bank/payment details against your agreed records. Export the final invoice, send it to the correct contact and keep a copy. Track the due date and follow up using the invoice number. Mark it paid only after reconciling the payment, not when the client says it is on its way.', ['Check each line item against approved work.', 'Verify the payment reference and due date.', 'Record the sent date and recipient.', 'Keep any later corrections linked to the original record.'], undefined, [link(invoice, 'Prepare an invoice with the free generator')])
    ], [['Does creating a PDF send the invoice?', 'No. Review and save the file, then send it through your agreed channel. The SkillLinkup tool does not email invoices or collect payments.'], ['Can I use the same tax rate for every client?', 'Do not assume that. The applicable treatment depends on your business and transaction. Check official guidance or obtain advice for your situation.']], [invoice, '/resources/essential-freelance-tools']),

  guide('upwork-pricing', 'Upwork Pricing: Freelancer Fees and What to Budget', 'Understand Upwork’s variable freelancer fee, proposal costs and net earnings. Use a worked example and check the fee shown for your contract.',
    'Upwork pricing is more than the amount shown on your profile. Separate the contract’s freelancer fee, the cost of finding work and any withdrawal, currency or tax costs that apply to your situation.',
    ['Read the fee displayed for the particular contract.', 'Budget for applying without assuming you will win.', 'Calculate net earnings before agreeing to the work.'], [
      section('The freelancer fee is contract-specific', 'Upwork currently describes its freelancer service fee as ranging from 0% to 15% per contract. Do not use the old flat 10% assumption for every new project. Read the displayed fee before accepting and check the official rules for any special programme or contract type.', [], upwork),
      section('Calculate the amount left after the fee', 'Illustrative arithmetic: for a $1,000 contract with a displayed 10% fee, the service fee is $100 and $900 remains before other costs and taxes. At a displayed 15%, $850 remains. These are scenarios, not a quote for your contract. To target a net amount N before other costs, divide N by (1 − the fee rate).', ['At 10%, targeting $900 before other costs requires $1,000 gross.', 'Allow for time spent on proposals, meetings and revisions.', 'Keep taxes and currency conversion separate from this calculation.']),
      section('Treat proposal spending as an acquisition cost', 'Connects and optional account features can add costs before you win a project. Check the purchase price, proposal requirement and renewal terms in your account; do not assume every application costs the same. Set a test budget and record qualified replies and paid work, so you can see whether the channel suits your offer.', [], ['Upwork: current freelancer plans', 'https://www.upwork.com/pricing/freelancer']),
      section('Compare the same scope and side of the transaction', 'A client’s checkout total and a freelancer’s earnings are different figures. When comparing platforms, keep the deliverables and contract value consistent and identify whose fee you are comparing. Check payout options available in your location and the applicable transaction terms before relying on a net figure.', [], undefined, [link('/resources/fiverr-vs-upwork', 'Compare Fiverr and Upwork'), link(choice, 'Choose a platform for your working model')])
    ], [['Does every freelancer pay 10%?', 'No. Check the contract-specific fee shown by Upwork and its current official fee guidance.'], ['Are the worked examples a quote?', 'No. They illustrate the arithmetic and exclude other costs and taxes. Your actual contract and account determine what applies.']], ['/resources/toptal-vs-upwork', '/resources/freelance-proposal-template'], { reviewed: '2026-09-08', translationKey: 'upwork-pricing' }),

  guide('platform-choice', 'How to Choose a Freelance Platform for Your Work', 'Choose a freelance platform by project type, client access, costs and working process. Includes a practical scorecard for testing your shortlist.',
    'The best freelance platform for you is the one where your offer fits the buying process and economics. Start with a project you can actually deliver, then compare how clients find, assess and pay for that work.',
    ['Define the project and buyer before the platform.', 'Compare the full working process and costs.', 'Test one channel with a clear time and money limit.'], [
      section('Match your offer to the buying process', 'A tightly scoped deliverable is easier to package than an open-ended consulting engagement. If discovery is necessary before pricing, look for a process that lets you clarify scope before committing. Write a sample brief and ask whether the platform helps both sides agree on that work.', [], undefined, [link(review, 'Understand the Fiverr package model'), link('/resources/toptal-vs-upwork', 'Compare Toptal and Upwork hiring models')]),
      section('Score your shortlist against your constraints', 'Use a simple 1–3 score for each criterion, with a written reason. Give a must-have more weight than a nice-to-have. A platform with many listings is still a poor fit if your target projects require languages, availability or credentials you cannot offer.', ['Demand: can you find relevant, credible briefs?', 'Economics: what remains after fees and unpaid acquisition time?', 'Process: can you define scope, revisions and approval?', 'Practical fit: are location, payout and communication requirements workable?'], undefined, [link('/resources/best-platform-designers', 'Platform choice for designers'), link(writers, 'Platform choice for writers'), link('/resources/best-freelance-platforms-marketing-consultants', 'Platform choice for marketing consultants')]),
      section('Run a small, measurable test', 'Choose one offer and one channel for a defined period. Record qualified opportunities, applications, replies, conversations, paid work and time spent. A quiet week is weak evidence; a full test with no relevant briefs may tell you to change the channel or offer. Do not pay for upgrades simply because the first proposals did not convert.'),
      section('Prepare proof before adding channels', 'Make sure your profile and portfolio explain the same service. When a buyer opens your application, they should quickly find a relevant example and understand your role. Add another channel only when you can maintain response times and delivery quality.', [], undefined, [link(portfolio, 'Build relevant portfolio case studies'), link(pricing, 'Account for Upwork costs')])
    ], [['Should beginners join every platform?', 'A focused test is easier to learn from. Maintaining several weak profiles can hide whether the problem is the offer, evidence or channel.'], ['Is the cheapest platform the best choice?', 'Only if it also fits the work. Compare net earnings and the time needed to acquire and manage projects.']], [portfolio, pricing], { path: choice }),

  guide('fiverr-review', 'Fiverr Pros and Cons: Is the Gig Model Right for You?', 'A practical Fiverr review of packaged services, seller earnings, scope and revisions. Decide when a Gig fits and when a different process is needed.',
    'Fiverr can fit work that a buyer can select and scope before ordering. Its package format is less straightforward when a project needs substantial discovery. This review evaluates that trade-off rather than assigning an unsupported universal score.',
    ['Make the package’s output and exclusions explicit.', 'Price for seller deductions and revision time.', 'Check custom requirements before committing.'], [
      section('The advantage: a concrete offer to compare', 'A package can make the first buying decision easier when the buyer understands the deliverable. Think of a defined illustration, edited recording or set of assets. The useful comparison is what is included, how feedback works and what files are delivered. A thumbnail and headline alone do not establish quality.', [], undefined, [link('/resources/how-to-hire-a-freelancer', 'Assess a freelancer against your brief')]),
      section('The trade-off: a small package can hide a large job', 'An unclear brief may turn one delivery into repeated revisions. State the required inputs, what counts as a revision and which requests need a new scope. For buyers, ask about source files, rights, dimensions and delivery formats before ordering. For sellers, avoid including unlimited work that you cannot price sustainably.'),
      section('Seller earnings and your working margin', 'Fiverr’s help page says sellers receive 80% of the purchase amount, including Gig Extras and tips. On an illustrative $100 order, that means $80 before other costs and taxes. Budget for communication, revisions and administration as well as production. The buyer’s checkout total is a separate calculation.', [], fiverr),
      section('When to consider another route', 'If the solution is not clear enough to package, begin with a properly scoped discovery step or choose a process designed for proposals and ongoing collaboration. Compare concrete briefs across channels rather than assuming one platform has universally better clients. SkillLinkup is preparing for launch; its waitlist is not an available substitute for ordering work today.', [], undefined, [link('/resources/fiverr-vs-upwork', 'Compare Fiverr with Upwork'), link(choice, 'Use a platform selection scorecard')])
    ], [['Is Fiverr only for inexpensive work?', 'A platform label does not define a project’s quality or total cost. Evaluate the actual scope, evidence and terms of the offer.'], ['Does a good rating replace portfolio review?', 'No. Check examples relevant to your own project and clarify who will do the work.']], [portfolio, pricing], { path: review, reviewed: '2026-09-08' }),

  guide('what-is-toptal', 'What Is Toptal? How Its Talent-Matching Model Works', 'Understand Toptal’s matching model, screening, client process and costs to check before hiring. Compare it with an open freelance marketplace.',
    'Toptal is a talent network that matches clients with professionals. The decision is whether you need help finding a specialist and evaluating a fit, rather than simply browsing a catalogue of fixed deliverables.',
    ['Define the role and expected work before matching.', 'Separate platform access costs from talent rates.', 'Agree on how the initial engagement will be evaluated.'], [
      section('Start with the role you need filled', 'Prepare the outcomes, required skills, weekly commitment and collaboration hours. Explain which decisions the specialist owns and who reviews the work. “Help with our product” leaves too much open; “implement an accessible checkout with the existing team” gives the matching conversation a useful starting point.', [], undefined, [link('/resources/how-to-hire-a-freelancer', 'Prepare your hiring brief')]),
      section('Understand the provider’s process', 'Toptal describes screening and a matching process in its client FAQ. Treat those as the provider’s description, not independent evidence that every proposed person is right for you. Review relevant experience and agree on a small, observable first milestone.', [], toptal),
      section('Ask for the full commercial picture', 'Request the proposed talent rate, expected commitment, platform charges and cancellation terms in writing. A headline rate cannot tell you the cost of an engagement without its hours and duration. Check the current terms directly before proceeding; avoid budgeting from old reviews or a generic salary comparison.'),
      section('Choose based on the hiring work you can do', 'A matching service may suit a team that wants assistance with the search. An open marketplace may suit a buyer prepared to shortlist and interview candidates. Either way, the brief and acceptance criteria remain your responsibility.', [], undefined, [link('/resources/toptal-vs-upwork', 'Compare Toptal and Upwork'), link('/resources/toptal-for-beginners', 'Read the Toptal beginner guide')])
    ], [['Is Toptal a fixed-price Gig catalogue?', 'Its matching model is different from choosing a predefined package. Clarify the engagement structure and quote with the provider.'], ['Does screening remove the need to assess fit?', 'No. Check experience against your project, collaboration needs and first deliverable.']], ['/resources/toptal-vs-upwork', '/resources/how-to-hire-a-freelancer'], { reviewed: '2026-09-08' }),

  guide('toptal-vs-upwork', 'Toptal vs Upwork: Compare the Hiring Process', 'Compare Toptal’s matching service with Upwork’s marketplace. Use the same brief to evaluate search effort, costs and engagement fit.',
    'Toptal and Upwork ask the buyer to do different amounts of hiring work. Compare the search and selection process first, then request costs for the same role and scope. A universal “cheaper” winner would hide those differences.',
    ['Use the same brief for both options.', 'Include your own selection and management time.', 'Review the engagement terms before starting.'], [
      section('Toptal: evaluate a matched specialist', 'Toptal describes a curated matching process in its FAQ. It may be worth considering when you want assistance finding a specialist. You still need to assess the proposed person against your project and define an initial deliverable. Confirm all commercial terms before starting.', [], toptal, [link('/resources/what-is-toptal', 'How Toptal’s model works')]),
      section('Upwork: prepare to assess candidates', 'Upwork offers a marketplace where clients and freelancers can establish contracts. If you use proposals, prepare a consistent shortlist and interview process. Compare similar work samples and ask every candidate the same scope questions; response volume alone does not tell you who can deliver.', [], ['Upwork: how the freelancer process works', 'https://www.upwork.com/i/how-it-works/freelancer/'], [link(pricing, 'Understand the freelancer side of Upwork pricing')]),
      section('Build a comparable cost sheet', 'Write one row each for professional fees, platform costs, expected hours, onboarding effort and optional expenses. Note which items are confirmed and which are estimates. Do not compare one platform’s client price to the other platform’s freelancer take-home amount.', ['Same role and seniority expectation.', 'Same weekly hours or deliverable list.', 'Same review, handover and support requirements.', 'Same currency and treatment of extra costs.']),
      section('Make the decision at the project level', 'For an ambiguous project, clarify requirements before deciding which channel to use. For a defined role, compare the available candidates and terms. If neither option produces convincing evidence, revise the brief or continue the search rather than choosing a platform because of a reputation claim.', [], undefined, [link(choice, 'Use the broader platform selection guide'), link('/resources/how-to-hire-a-freelancer', 'Review your hiring checklist')])
    ], [['Which platform is cheaper?', 'Compare actual quotes for the same work and include platform costs and your own hiring effort. Generic hourly ranges cannot answer that reliably.'], ['Can either platform guarantee project success?', 'Your scope, candidate fit, collaboration and acceptance process still matter. Read the specific contractual protections rather than assuming a guarantee.']], ['/resources/what-is-toptal', pricing], { reviewed: '2026-09-08' }),

  guide('best-time-tracking-tools-freelancers', 'Time-Tracking Tools for Freelancers: What to Compare', 'Compare Toggl Track, Clockify and a simple timesheet by reporting workflow. Check exports, billable work and client approval before picking a plan.',
    'The best time tracker is one you will keep accurate and can use to produce the record you need. Compare a normal working week and a sample client report before committing to a tool or subscription.',
    ['Track a real workflow, including corrections.', 'Check the export available on your intended plan.', 'Keep private notes out of client reports.'], [
      section('Toggl Track: test the reporting workflow', 'Toggl Track provides reporting for tracked work. Try grouping time by client and project, correcting a forgotten entry and producing the report you would send with an invoice. Verify the required features and export formats on the plan you intend to use.', [], ['Toggl Track: reporting', 'https://toggl.com/track/reporting/']),
      section('Clockify: check the export before deciding', 'Clockify provides reports that break down tracked time and costs. Export options and plan requirements can differ, so check its current export documentation. Use a sample that includes a correction, non-billable work and more than one project; a basic timer demonstration is not enough to test reporting.', [], ['Clockify: exporting reports', 'https://clockify.me/help/reports/exporting-reports']),
      section('A spreadsheet: a reasonable baseline', 'For simple work, a timesheet may be sufficient if you maintain it consistently. Use date, client, project, description, duration and billable status as separate columns. Keep a protected copy of approved records. A manual sheet becomes less attractive when you need permissions, frequent reports or integrations.'),
      section('Evaluate the record, not only the timer', 'Before choosing, complete a sample day, correct an entry, review the total and export the result. Ask whether the client can understand what was done without seeing confidential internal notes. For fixed-price work, use time data to assess your estimating accuracy without changing the agreed billing model.', [], undefined, [link(invoicing, 'Connect time records to invoicing'), link('/resources/essential-freelance-tools', 'Fit time tracking into your tool setup')])
    ], [['Do fixed-price freelancers need time tracking?', 'It can help compare estimated and actual effort. It does not automatically convert a fixed-price agreement into hourly billing.'], ['Should I choose the free plan?', 'Check whether it supports the reporting period, exports and permissions you need. Compare current plan terms using your sample workflow.']], [invoicing, '/resources/essential-freelance-tools'], { reviewed: '2026-09-08' }),

  guide('best-platform-designers', 'Freelance Platforms for Designers: Choose by Project Type', 'Choose a platform for freelance design work by deliverables, portfolio fit and feedback process. Compare packages, proposals and specialist matching.',
    'A logo package, a website redesign and an embedded product-design role need different buying processes. Choose a platform by the work you want to deliver, then show evidence for that exact kind of project.',
    ['Name the design deliverable and its boundaries.', 'Show work that fits the buyer’s problem.', 'Agree on feedback, files and usage rights.'], [
      section('Defined assets: compare a package workflow', 'For clearly bounded design work, a package can make scope easy to understand. Fiverr is one option to evaluate for this model. Check whether the buyer knows what they need before ordering and whether you can price revisions, formats and source-file handover clearly.', [], undefined, [link(review, 'Review the advantages and limits of Fiverr')]),
      section('Collaborative projects: compare a proposal workflow', 'Website and product work often require discovery, access to existing assets and several review points. Compare whether the hiring channel gives you enough opportunity to clarify those inputs. On a proposal-based project, name stages rather than offering an undefined number of design hours.', [], undefined, [link('/resources/toptal-vs-upwork', 'Compare marketplace and matching models')]),
      section('Build a design-specific selection checklist', 'Use two representative projects to compare channels. For example, price a small brand asset set separately from a multi-page interface. Check whether clients in that channel ask for your kind of work and whether their expectations match your delivery process.', ['Who supplies copy and brand assets?', 'How are feedback and approval recorded?', 'Which editable files and exports are included?', 'What happens if the visual direction changes after approval?']),
      section('Make the portfolio do the screening', 'Show the problem, constraints, decisions and actual deliverables. Do not rely on polished mockups alone. A relevant case study helps a buyer understand whether you can handle their project before either side spends time in a call.', [], undefined, [link(portfolio, 'Build a portfolio that explains your design work'), link('/services/graphic-design', 'Define a graphic design brief')])
    ], [['Which platform is best for every designer?', 'There is no single answer across packaged assets, full websites and ongoing product roles. Start with the project and buying process.'], ['Should I compete on price first?', 'Check that the price covers production, communication and revisions. A low price with unclear scope is difficult to sustain.']], [choice, portfolio]),

  guide('best-platform-writers', 'Freelance Platforms for Writers: Match the Channel to the Work', 'Compare freelance writing platforms by briefs, editorial process and project economics. Choose a channel for articles, content or conversion copy.',
    'A freelance writing platform should connect you with briefs that fit your subject knowledge and writing process. Compare the editorial work behind an assignment, not just its word count or advertised budget.',
    ['Specify the audience, format and subject.', 'Count research and revision time in the price.', 'Use relevant samples with a clear explanation of your role.'], [
      section('Separate content writing from conversion copy', 'An expert article may need interviews, citations and editorial review. A landing page may need offer research, message testing and design collaboration. These are different services even when the final word count is similar. Present an offer that describes the work the client will receive.', [], undefined, [link('/resources/platforms-for-copywriters', 'Compare channels for copywriting projects')]),
      section('Compare packages and proposals', 'A repeatable deliverable with known inputs can fit a package model. Assignments with uncertain research, stakeholders or scope need more discussion. Use the Fiverr review and Upwork cost guide to compare those routes, then inspect actual briefs in your niche rather than relying on platform-wide claims.', [], undefined, [link(review, 'When a packaged Fiverr offer fits'), link(pricing, 'Budget for finding work on Upwork')]),
      section('Check the editorial process before quoting', 'Ask who approves the outline, whether interviews are required and how feedback will be consolidated. Identify the intended publication channel, attribution and reuse requirements. Agree how a new angle after outline approval affects scope.', ['Reader and purpose of the piece.', 'Source material and interview responsibilities.', 'Outline approval and revision rounds.', 'Delivery format, attribution and usage terms.']),
      section('Test with a relevant sample', 'Show a sample that resembles the work the buyer needs. Explain the brief, audience and your contribution. Label unpublished examples as samples. Do not promise traffic or sales from a piece whose distribution and implementation are outside your control.', [], undefined, [link(portfolio, 'Structure a useful writing case study'), link('/resources/freelance-proposal-template', 'Write a proposal with clear deliverables')])
    ], [['Should I price only by the word?', 'Word count does not capture research, interviews, revisions or strategic work. Use it only when it matches a clearly defined scope.'], ['Can beginners use sample articles?', 'Yes. Label them honestly and choose subjects you can research and explain accurately.']], [choice, portfolio], { translationKey: 'writers' }),

  guide('platforms-for-copywriters', 'Freelance Platforms for Copywriters: Find the Right Brief', 'Evaluate copywriting channels for landing pages, email and campaign work. Compare buyer readiness, portfolio evidence and scope before applying.',
    'Copywriting projects depend on the offer, audience and distribution as much as the final text. Look for a channel where you can clarify those inputs and show relevant thinking before a client commits.',
    ['Define the offer and audience.', 'Include research and feedback in the scope.', 'Show decisions without inventing conversion results.'], [
      section('Start with the asset and its job', 'Distinguish an email sequence from a landing page, ad concepts or a full message strategy. List the inputs needed for that asset: customer evidence, offer details, brand voice and design constraints. If the client cannot supply them, scope discovery explicitly.'),
      section('Choose a process that allows clarification', 'Compare a packaged service with a proposal-based engagement. A repeatable editing task may fit a package; an unclear offer usually needs a conversation. Evaluate the Fiverr and Upwork models against your own brief rather than promising a platform with better clients.', [], undefined, [link(review, 'Evaluate Fiverr’s Gig model'), link(pricing, 'Check Upwork project economics')]),
      section('Show the reasoning behind your copy', 'Present the audience problem, message hierarchy and alternatives you considered. Include results only when you can explain the measurement and your contribution. A clear before-and-after edit can demonstrate skill without an unsupported sales claim.', [], undefined, [link(portfolio, 'Build an evidence-based copywriting portfolio')]),
      section('Agree on testing and responsibility', 'State whether implementation, analytics and experimentation are included. Delivery of copy and proof of a business outcome are separate milestones. Name the approver, revision limits and what changes if the offer changes. This keeps the project reviewable for both sides.', [], undefined, [link('/resources/freelance-proposal-template', 'Define the copywriting engagement')])
    ], [['Is copywriting the same as writing articles?', 'The deliverable, reader action and research can differ. Describe the service precisely so the client can compare like-for-like offers.'], ['Should I guarantee conversions?', 'Do not promise an outcome you cannot control or substantiate. Agree on deliverables and any testing responsibilities instead.']], [writers, portfolio]),

  guide('optimizing-freelance-profile-maximum-visibility', 'Optimize Your Freelance Profile for Relevant Enquiries', 'Make your freelance profile clear with a focused headline, relevant proof and a practical next step. Avoid keyword stuffing and unsupported claims.',
    'A strong freelance profile lets the right client recognise your offer quickly. Use the words they use for the work, support them with examples and explain what information you need to discuss a project.',
    ['Lead with the service and the client it fits.', 'Support your offer with relevant work.', 'Make the next conversation easy to start.'], [
      section('Write a headline with one clear promise', 'Name the service, then add a meaningful specialism if you have one. “Web designer for service businesses” is easier to assess than a string of unrelated roles. Do not add credentials, years of experience or results you cannot substantiate.', [], undefined, [link(choice, 'Align your profile with your chosen channel')]),
      section('Use the opening to explain fit', 'In a short paragraph, explain what you make, who it serves and the common scope. Then describe the process: inputs, collaboration, review and handover. Repeat keywords only when they help the reader; a list of near-identical phrases makes the profile harder to use.'),
      section('Connect each claim to evidence', 'Put the closest portfolio example next to the relevant service. If you say you design responsive websites, show the responsive work and explain your contribution. If you work with a particular sector, demonstrate relevant understanding rather than listing industries indiscriminately.', [], undefined, [link(portfolio, 'Prepare portfolio evidence for your profile')]),
      section('Review enquiry quality, not just views', 'Track whether conversations match your service, budget and availability. If the wrong projects keep arriving, clarify the scope and exclusions. Ask prospective clients for a short brief and timeline so you can respond usefully. Profile wording alone cannot guarantee platform visibility.', [], undefined, [link('/resources/freelance-proposal-template', 'Turn a qualified enquiry into a proposal')])
    ], [['Should I repeat keywords throughout my profile?', 'Use accurate terms naturally. Clear evidence and a coherent offer are more useful to a reader than repeated synonyms.'], ['Does a profile rewrite guarantee more work?', 'No. Demand, competition, experience and your response process also affect results. Monitor relevant enquiries after changes.']], [portfolio, choice], { translationKey: 'profile' }),

  guide('best-freelance-platforms-marketing-consultants', 'Freelance Platforms for Marketing Consultants: A Selection Guide', 'Choose a channel for freelance marketing consulting by scope, access, measurement and commercial fit. Use a practical client-readiness checklist.',
    'Marketing consulting works best when a client can define the business question and provide the access needed to investigate it. Compare platforms by how well their hiring process supports that conversation.',
    ['Separate advice from hands-on execution.', 'Define what data and access the work needs.', 'Agree on deliverables and measurement limits.'], [
      section('Package an audit only when the inputs are clear', 'A defined review can be a useful first engagement if the client can supply the required material. State which channels, accounts or pages are included and what the output contains. Do not promise a full growth strategy from a brief that only covers one landing page.'),
      section('Use a proposal process for ongoing work', 'Ongoing consulting needs clarity about meetings, implementation ownership and reporting. Compare marketplace proposals and specialist matching against the same scope. Include the time a client must spend providing information and acting on recommendations.', [], undefined, [link('/resources/toptal-vs-upwork', 'Compare two hiring processes'), link(choice, 'Score your platform shortlist')]),
      section('Check client readiness', 'Before quoting, ask whether the necessary data exists and who can provide access. Confirm the decision-maker, budget authority and implementation owner. If tracking is missing, make the first phase a measurement and discovery task rather than a promise of rapid results.', ['What business question must the engagement answer?', 'Which baseline and data sources are available?', 'Who approves and implements recommendations?', 'What can realistically be delivered in the agreed period?']),
      section('Demonstrate a method and its limits', 'Use a case study that explains the diagnosis, action and evidence. Distinguish your work from changes made by other teams or market conditions. A useful deliverable might be a prioritised SEO backlog with acceptance criteria; a guaranteed ranking is not a substitute for that work.', [], undefined, [link('/services/seo', 'Scope an SEO project'), link(portfolio, 'Present a consulting case study')])
    ], [['Should consultants guarantee revenue growth?', 'Only make claims you can support. Revenue depends on implementation and other conditions beyond the consultant’s work; agree on concrete deliverables and measurement.'], ['Is an audit a good first project?', 'It can be, when the question, inputs and output are defined. Avoid selling a generic report that does not support a decision.']], [choice, '/services/seo']),

  guide('ai-tools-for-freelancers', 'AI Tools for Freelancers: Choose a Useful, Reviewable Workflow', 'Evaluate AI tools for drafting, research support and administration. Compare data handling, output quality and review effort before adding a tool.',
    'Choose an AI tool for a specific task you can check. Drafting a project outline, organising your own notes and suggesting alternatives are different from relying on a tool to establish facts or make client commitments.',
    ['Choose one task with a clear acceptance test.', 'Check data handling before using client material.', 'Include human review time in the cost.'], [
      section('Start with a bounded task', 'Pick a repetitive step where you can recognise a good result. For example, turn your own meeting notes into a draft action list, then verify each owner and deadline. Keep the original notes so you can compare. Do not allow the tool to send the draft or make commitments without review.'),
      section('Compare tools with the same sample', 'Use non-confidential sample material and ask each tool to produce the same output. Assess accuracy, completeness, editing effort and export quality. Count the time needed to correct the result. A fast first draft is not a saving if it takes longer to verify than doing the task yourself.'),
      section('Check permissions and current product terms', 'Before uploading client information, confirm you are allowed to use it with that provider and review its current data retention, training and account settings. Capabilities and terms change; this is a workflow guide rather than a fixed ranking of products. Use public or synthetic examples for evaluation.'),
      section('Keep responsibility for the delivered work', 'Verify factual claims against original sources. Check licensing and client requirements for generated assets. Keep approved deliverables separate from drafts and explain AI use when your agreement requires it. The invoice tool on this site uses entered values and arithmetic; it does not use AI to decide tax or invent billing details.', [], undefined, [link('/resources/essential-freelance-tools', 'Build a practical freelance tool setup'), link(invoice, 'Use the non-AI invoice generator')])
    ], [['Do I need an AI subscription to freelance?', 'No. Use a tool only when a tested workflow helps your work enough to justify its cost and review effort.'], ['Can an AI answer replace a source?', 'No. Verify material claims using the original evidence, especially before publishing or advising a client.']], ['/resources/essential-freelance-tools', '/resources/freelance-proposal-template']),
];

recoveryPages.push(
  guide('upwork-pricing', 'Upwork-kosten: platformfee en netto-opbrengst', 'Bekijk hoe je de Upwork-platformfee, acquisitiekosten en netto-opbrengst beoordeelt. Met een rekenvoorbeeld en links naar actuele voorwaarden.',
    'Bereken bij Upwork wat een opdracht oplevert nadat de contractfee is verwerkt. Houd kosten voor het vinden van werk, valuta en belastingen apart, zodat je geen bruto-opdrachtwaarde verwart met netto-inkomen.',
    ['Controleer de fee bij het specifieke contract.', 'Reserveer een apart acquisitiebudget.', 'Neem ook overleg en revisies mee in je raming.'], [
      section('Controleer het percentage per contract', 'Upwork vermeldt momenteel een freelancerfee van 0% tot 15% per contract. Ga dus niet bij iedere nieuwe opdracht automatisch uit van 10%. Controleer het getoonde percentage voordat je akkoord gaat en lees de officiële uitleg voor uitzonderingen.', [], upwork),
      section('Een eenvoudig rekenvoorbeeld', 'Bij een voorbeeldopdracht van $1.000 met een getoonde fee van 10% blijft $900 over vóór andere kosten en belastingen. Bij 15% blijft $850 over. Dit zijn rekenvoorbeelden, geen offerte voor jouw account. Tel je verwachte uren voor overleg, uitvoering en revisies op om te bepalen of de opdracht past.'),
      section('Begroot ook het vinden van werk', 'Solliciteren en optionele accountfuncties kunnen kosten meebrengen voordat je een opdracht hebt. Controleer de actuele prijzen en voorwaarden in je account. Houd bij hoeveel passende reacties en betaalde opdrachten je inspanning oplevert, zodat je een kanaal op meer beoordeelt dan profielweergaven.'),
      section('Vergelijk gelijkwaardige bedragen', 'Het totaal dat een opdrachtgever betaalt is iets anders dan de opbrengst van een freelancer. Vergelijk dezelfde scope, valuta en kant van de transactie. Controleer uitbetaling en eventuele aanvullende kosten afzonderlijk.', [], undefined, [link('/nl/resources/how-to-stand-out-on-crowded-freelance-platforms', 'Maak je freelanceprofiel concreet')])
    ], [['Is de fee altijd 10%?', 'Nee. Gebruik het percentage dat Upwork bij jouw contract toont en controleer de actuele voorwaarden.'], ['Zijn belastingen in het voorbeeld verwerkt?', 'Nee. Het voorbeeld laat alleen het effect van de genoemde platformfee zien.']], ['/nl/resources/best-platforms-freelance-writers-content-creators'], { path: '/nl/resources/upwork-pricing', locale: 'nl', reviewed: '2026-09-08', translationKey: 'upwork-pricing' }),
  guide('best-platforms-freelance-writers-content-creators', 'Freelanceplatforms voor schrijvers en contentmakers kiezen', 'Kies een freelancekanaal dat past bij je schrijfwerk, onderzoek en redactieproces. Met praktische vragen over scope, voorbeelden en vergoeding.',
    'Een passend platform brengt je in contact met opdrachten waarvoor jouw kennis en schrijfproces relevant zijn. Kijk verder dan het aantal woorden: onderzoek, interviews, feedback en publicatie bepalen samen het werk.',
    ['Benoem doelgroep, onderwerp en formaat.', 'Neem onderzoek en revisies op in de scope.', 'Laat relevante voorbeelden zien.'], [
      section('Maak je schrijfaanbod specifiek', 'Een interviewartikel, SEO-gids en landingspagina vragen verschillende input. Beschrijf voor welk type opdrachtgever je werkt en wat je oplevert. Vermijd een profiel dat ieder denkbaar schrijfdienstje opsomt zonder te laten zien waar je goed in bent.'),
      section('Kies een werkbare opdrachtstructuur', 'Een herhaalbare tekst met duidelijke input kan als pakket worden aangeboden. Een opdracht met onzekere onderzoeksvragen of veel betrokkenen vraagt eerst om overleg. Beoordeel concrete briefs en de manier waarop je afspraken kunt vastleggen, niet alleen de bekendheid van het platform.', [], undefined, [link('/nl/resources/upwork-pricing', 'Bereken de kosten van een Upwork-opdracht')]),
      section('Stel vragen vóór je een prijs afgeeft', 'Vraag wie het onderwerp en de opzet goedkeurt, wie bronnen aanlevert en hoe feedback wordt verzameld. Leg vast of interviews, beeldselectie en publicatie inbegrepen zijn. Een nieuw onderwerp na goedkeuring van de opzet is een andere vraag dan een normale correctieronde.', ['Voor wie is de tekst bedoeld?', 'Welke bronnen en interviews zijn nodig?', 'Wie is de eindredacteur of beslisser?', 'Welke revisies en gebruiksrechten worden afgesproken?']),
      section('Laat passend werk zien', 'Toon een voorbeeld dat lijkt op de gewenste opdracht en beschrijf jouw rol. Noem een zelfgeschreven voorbeeld ook echt een voorbeeld. Beloof geen bezoekersaantallen of verkopen die je niet kunt onderbouwen. Gebruik reacties op je aanbod om de afbakening verder aan te scherpen.', [], undefined, [link('/nl/resources/how-to-stand-out-on-crowded-freelance-platforms', 'Verduidelijk je freelanceprofiel')])
    ], [['Moet ik per woord rekenen?', 'Alleen als dat past bij een duidelijk afgebakende opdracht. Woorden tellen maakt onderzoek, overleg en revisies niet automatisch zichtbaar.'], ['Kan ik zonder betaalde opdrachten voorbeelden tonen?', 'Ja. Label eigen voorbeelden eerlijk en kies onderwerpen die je zorgvuldig kunt onderzoeken.']], ['/nl/resources/upwork-pricing'], { locale: 'nl', path: '/nl/resources/best-platforms-freelance-writers-content-creators', translationKey: 'writers' }),
  guide('how-to-stand-out-on-crowded-freelance-platforms', 'Opvallen op freelanceplatforms met een duidelijk profiel', 'Maak je freelanceprofiel concreet met een herkenbaar aanbod, relevant portfolio en duidelijke vervolgstap. Zonder keywordspam of onbewezen claims.',
    'Opvallen begint met herkenbaarheid: de juiste opdrachtgever moet kunnen zien wat je maakt, voor wie en waarom je daarvoor geschikt bent. Een concreet aanbod helpt meer dan een profiel vol algemene kwaliteiten.',
    ['Begin met één herkenbare dienst.', 'Onderbouw je aanbod met passend werk.', 'Maak duidelijk welke projectinformatie je nodig hebt.'], [
      section('Schrijf een specifieke kop', 'Noem het werk dat je aanbiedt en voeg een specialisme toe als je dat kunt onderbouwen. “Webdesigner voor zakelijke dienstverleners” vertelt meer dan een reeks losse functietitels. Gebruik geen verzonnen certificaten, ervaringsjaren of resultaten.'),
      section('Leg je werkwijze uit', 'Beschrijf welke input je nodig hebt, hoe feedback verloopt en wat je overdraagt. Zo kan een opdrachtgever zich een samenwerking voorstellen. Gebruik relevante woorden op een natuurlijke manier in plaats van dezelfde zoekterm steeds te herhalen.'),
      section('Koppel bewijs aan je dienst', 'Laat bij iedere belangrijke belofte een passend voorbeeld zien. Benoem jouw bijdrage en die van anderen. Als er geen meetbaar bedrijfsresultaat is, toon dan het gemaakte werk en de keuzes die je hebt gemaakt. Een eerlijk voorbeeld is bruikbaarder dan een niet te controleren succesclaim.'),
      section('Meet passende gesprekken', 'Beoordeel of aanvragen aansluiten op je dienst, planning en tarief. Komen steeds verkeerde opdrachten binnen, verduidelijk dan de scope en uitsluitingen. Meer profielweergaven zijn geen doel op zich en een tekstwijziging garandeert geen hogere zichtbaarheid.', [], undefined, [link('/nl/resources/best-platforms-freelance-writers-content-creators', 'Een kanaal kiezen voor schrijfwerk'), link('/nl/resources/upwork-pricing', 'Je opdrachtmarge beoordelen')])
    ], [['Helpt veel herhalen van keywords?', 'Gebruik woorden die je werk accuraat beschrijven. Herhaling zonder extra informatie maakt een profiel moeilijker leesbaar.'], ['Garandeert een beter profiel meer opdrachten?', 'Nee. Ook vraag, concurrentie, ervaring en je reactieproces spelen een rol. Kijk naar relevante aanvragen na een wijziging.']], ['/nl/resources/best-platforms-freelance-writers-content-creators'], { locale: 'nl', path: '/nl/resources/how-to-stand-out-on-crowded-freelance-platforms', translationKey: 'profile' })
);
