import { recoveryPages } from './recovery';
// One search intent per URL. These English editorial routes are maintained in git.
export const seoPages = [
  {
    slug: 'webdesign', path: '/services/webdesign', type: 'service', keyword: 'hire web designer', skill: 'Web design',
    title: 'Hire a Web Designer: Plan Your Website Project',
    description: 'Prepare to hire a web designer: compare portfolios, define your website scope and plan the handover. Join the SkillLinkup launch waitlist.',
    intro: 'Hire a web designer for the experience your visitors need, not just the look of a homepage. Start with the pages, actions and content your website must support, then compare designers against that brief.',
    example: ['Goal: turn service enquiries into booked consultations.', 'Scope: home, services, about, contact and one reusable service template.', 'Handover: editable design files, responsive layouts and a walkthrough.'],
    sections: [
      { title: 'Choose the kind of web design help you need', body: 'A visual redesign, a working website and a usability review are different projects. A designer may deliver layouts without building them. A developer may implement a design without writing the content. Ask who owns each part before comparing quotes.', items: ['A new website: agree the page list, content owner and platform before design starts.', 'A redesign: identify what is confusing today and which existing content must stay.', 'An online store: include product pages, checkout states and mobile shopping flows.', 'UX/UI support: specify the journeys, screen states and prototype you need.'] },
      { title: 'Write a brief that makes quotes comparable', body: 'Describe your audience and the one action a visitor should take. Include your current URL, required pages, examples you like and why, content readiness, budget range and target launch date. Say whether the quote should include development, copywriting, images and ongoing maintenance.', items: ['Separate must-have features from later improvements.', 'Name the person who consolidates feedback and approves each stage.', 'List integrations such as booking, payments or a newsletter form.', 'Agree how extra pages or revised scope will be priced.'] },
      { title: 'Read portfolios beyond the screenshots', body: 'Ask what the designer personally contributed to each example. Open the live website on a phone, try its navigation and inspect a complete journey rather than only the hero section. A beautiful mockup does not tell you whether the contact form works or whether the business can edit its own pages.', items: ['How did the original brief shape the design?', 'What happens when headings are longer or an image is missing?', 'How will keyboard navigation, contrast and form labels be checked?', 'Who will build, test and maintain the finished site?'] },
      { title: 'Agree milestones and a usable handover', body: 'A practical sequence is brief approval, page structure, visual direction, remaining layouts, implementation and final checks. Define what you will review at each stage and how many feedback rounds are included. Keep domain and hosting ownership explicit. Before sign-off, request the files, access and instructions your team needs to maintain the work.' },
    ],
    faq: [['How much does it cost to hire a web designer?', 'The scope matters more than a universal price. Page count, custom interactions, content, development and revisions all affect a quote. Give each candidate the same brief and compare included deliverables, not only the total.'], ['Should I hire a web designer or a developer?', 'Choose design support when you need layouts, visual direction or user flows. Choose development support when you need those designs built. For a complete website, confirm who handles both and who tests the finished result.'], ['Can I hire through SkillLinkup today?', 'SkillLinkup is preparing for launch. Join the waitlist for a launch update; joining does not book a designer or guarantee a match.']],
    related: ['/resources/how-to-hire-a-freelancer', '/services/graphic-design', '/services/seo'],
  },
  {
    slug: 'graphic-design', path: '/services/graphic-design', type: 'service', keyword: 'hire graphic designer', skill: 'Graphic design',
    title: 'Hire a Graphic Designer: Brief, Portfolio & Deliverables',
    description: 'Learn what to prepare before you hire a graphic designer, from portfolio questions to editable files. Join the SkillLinkup waitlist for launch updates.',
    intro: 'Hire a graphic designer with a specific use in mind: a recognisable identity, a clear presentation or campaign assets that work across channels. Define where the work will appear before choosing a style or requesting a quote.',
    example: ['Goal: a consistent identity for a new consulting business.', 'Scope: logo, colour palette, typography and a short brand guide.', 'Handover: editable originals plus agreed web and print exports.'],
    sections: [
      { title: 'Match the designer to the deliverable', body: 'Brand identity, editorial layout, packaging and social graphics need different experience. Look for complete projects similar to the work you need. A strong illustration portfolio can be valuable, but it does not automatically demonstrate production-ready packaging or a reusable presentation system.', items: ['Brand identity: logo variants, colour and type guidance, and usage examples.', 'Marketing assets: named formats, dimensions and the number of variations.', 'Presentations: slide templates, chart styles and editable layouts.', 'Print: final dimensions, supplier specifications and agreed production files.'] },
      { title: 'Give creative direction without designing the answer', body: 'Explain the audience, message and business context. Share the words and images that must appear, existing brand rules and examples with a short explanation of what you like. “Make it modern” leaves too much to interpretation; “make the headline easy to scan on a small phone screen” describes a useful constraint.' },
      { title: 'Ask how the portfolio work was made', body: 'Ask the designer to walk through one relevant project: the brief, options considered, feedback and final deliverables. Confirm whether they created the identity, adapted an existing system or worked as part of a team. Where client results are mentioned, ask what was actually measured rather than assuming the design caused every improvement.', items: ['What would you need from us before the first concept?', 'How many creative directions and revision rounds are included?', 'How do you prepare files for our intended channels?', 'Which work depends on licensed fonts, stock assets or third-party tools?'] },
      { title: 'Agree files, revisions and future use', body: 'List the editable source formats and exports you need before work begins. A flattened image may be enough for one advert but inconvenient for a template your team will reuse. Ask which assets require separate licences and document the agreed usage permissions. For print, let the printer confirm technical requirements before final export. Keep one feedback owner so conflicting comments do not turn into extra rounds.' },
    ],
    faq: [['What should I send a freelance graphic designer?', 'Send the purpose, audience, exact deliverables, existing brand assets, final copy, dimensions, deadline and budget range. Clearly mark anything that is still awaiting approval.'], ['Will I receive editable files?', 'Only if that is part of the agreed scope. Specify the software format, exports and any fonts or assets needed to edit the work before accepting the quote.'], ['Is the SkillLinkup waitlist a design order?', 'No. It registers your interest in the launch. You can add graphic design as your interest without committing to a project.']],
    related: ['/resources/how-to-hire-a-freelancer', '/services/webdesign', '/resources/freelance-proposal-template'],
  },
  {
    slug: 'seo', path: '/services/seo', type: 'service', keyword: 'freelance seo specialist', skill: 'SEO',
    title: 'Freelance SEO Specialist: How to Choose the Right Support',
    description: 'Compare freelance SEO specialists by scope, evidence and reporting. Prepare a useful SEO brief and join the SkillLinkup launch waitlist.',
    intro: 'A freelance SEO specialist should help you identify which search problems are worth solving and explain how the work will be evaluated. Start with your website, customers and business goals before asking for a list of keywords.',
    example: ['Goal: help relevant buyers discover our service pages.', 'Scope: indexing review, search intent mapping and a prioritised action plan.', 'Handover: recommendations with owners, implementation steps and measurement.'],
    sections: [
      { title: 'Decide what kind of SEO support you need', body: 'An audit identifies issues; implementation changes the website. Content planning and ongoing reporting are separate work too. Ask the specialist to distinguish recommendations from work they will actually deliver, and confirm whether a developer or writer is needed.', items: ['Technical SEO: crawling, indexing, page templates and site architecture.', 'On-page SEO: search intent, useful copy, titles and internal links.', 'Content planning: distinct topics, briefs and improvements to existing pages.', 'Ongoing support: reviewing performance and choosing the next useful changes.'] },
      { title: 'Prepare a brief with business context', body: 'Share the website, target language and countries, important services and the action you want visitors to take. Mention recent migrations, redesigns or major traffic changes. Describe the resources available for implementation. An extensive audit is less useful if nobody can act on its recommendations. Agree suitable account permissions before granting access.' },
      { title: 'Evaluate the reasoning, not a ranking promise', body: 'Ask for an example of a recommendation, why it mattered and how the result was assessed. A credible proposal explains uncertainty and dependencies. Google warns against guarantees of a number-one ranking. Ask what the specialist will change, what they need from you and how they avoid tactics that violate search policies.', items: ['Which pages or user journeys would you investigate first, and why?', 'How do you separate branded searches from new customer discovery?', 'What evidence would make you change the initial plan?', 'How will you document changes so another person can maintain the site?'], source: ['Google: Do you need an SEO?', 'https://developers.google.com/search/docs/fundamentals/do-i-need-seo'] },
      { title: 'Measure progress against the actual goal', body: 'Agree a baseline and reporting cadence. Search impressions and clicks help show visibility; relevant enquiries or waitlist registrations show whether visitors take the intended next step. Rankings alone do not describe lead quality. Record meaningful site changes alongside results and avoid treating a short-term fluctuation as proof of success or failure.' },
    ],
    faq: [['What does a freelance SEO specialist do?', 'Depending on the scope, they review technical issues, map search intent, improve pages, plan content and report on performance. Ask which tasks include implementation and which are recommendations only.'], ['Can an SEO specialist guarantee first place?', 'No trustworthy hiring decision should depend on that promise. Search results depend on factors outside one specialist’s control. Agree concrete deliverables and measurement instead.'], ['Can I find an SEO specialist on SkillLinkup now?', 'The platform is preparing for launch. Join the waitlist to register your interest in SEO support and receive a launch update.']],
    related: ['/services/webdesign', '/resources/how-to-hire-a-freelancer', '/services/graphic-design'],
  },
  {
    slug: 'how-to-hire-a-freelancer', path: '/resources/how-to-hire-a-freelancer', type: 'guide', keyword: 'how to hire a freelancer', skill: '',
    title: 'How to Hire a Freelancer: A Practical Project Checklist',
    description: 'Learn how to hire a freelancer with a clear brief, relevant portfolio questions, agreed milestones and a practical handover checklist.',
    intro: 'To hire a freelancer, define the outcome, shortlist people with relevant work, compare the same scope and agree how delivery will be accepted. A small, clear brief is a better starting point than a long list of loosely connected tasks.',
    example: ['Outcome: what should be different when the project is complete?', 'Deliverables: which files, pages or tasks will you receive?', 'Acceptance: how will both sides know the work is ready?'],
    sections: [
      { title: '1. Describe the result before the job title', body: '“We need a designer” is a starting point. “We need a five-page website that explains our services and collects enquiries” is a scope you can discuss. Note your audience, current situation, required deliverables and deadline. Include a budget range if you have one, and name any constraints such as a required platform or brand system.' },
      { title: '2. Separate essentials from optional work', body: 'Make a short must-have list and a separate later list. Confirm who provides copy, images, access and feedback. A freelancer cannot give a reliable delivery date when key inputs are still unknown. If the problem itself needs investigation, consider a paid discovery stage with a defined output before commissioning the full project.' },
      { title: '3. Shortlist using relevant evidence', body: 'Choose portfolio examples that resemble your problem, not just the visual style you like. Ask what the freelancer personally did and what was outside their role. Reviews can add context, but read for communication, delivery and relevance. Avoid requesting unpaid custom work as a substitute for assessing an existing portfolio.', items: ['Ask for a walkthrough of one relevant project.', 'Confirm availability, working hours and the preferred feedback channel.', 'Discuss who will do the work if a team or subcontractor is involved.', 'Ask what information is needed to produce a firm proposal.'] },
      { title: '4. Compare proposals on the same basis', body: 'Compare deliverables, exclusions, revision rounds, schedule, payment stages and handover. The cheapest total may cover less. Ask candidates to clarify gaps rather than assuming they included everything in your brief. For larger projects, agree milestones that produce something you can review, such as an approved structure or a working feature.' },
      { title: '5. Keep feedback specific and consolidated', body: 'Use one place for decisions and one person to consolidate comments. Describe what is not working and why rather than sending contradictory redesign instructions. When the scope changes, agree the effect on price and timing before work continues. Keep a written record of approvals so both sides know which version is current.' },
      { title: '6. Check the handover before closing the project', body: 'Review the work against the original acceptance criteria. Confirm that the files open, access is transferred appropriately and instructions are understandable. Agree how any final issues will be handled. If ongoing support is needed, define that separately instead of assuming it is included forever.', items: ['Receive the agreed editable files and exports.', 'Test important journeys and links where applicable.', 'Document account ownership and ongoing service costs.', 'Record any outstanding tasks with an owner and due date.'] },
    ],
    faq: [['Should I start with a small project?', 'A small paid milestone can help both sides test collaboration when it produces a useful result. Keep its scope and acceptance criteria explicit; do not treat it as a request for free speculative work.'], ['What if I do not know my budget yet?', 'Describe the outcome and ask which parts could fit into a first phase. Compare a reduced scope with a fuller version rather than asking for an unlimited project at an unspecified price.']],
    related: ['/services/webdesign', '/services/graphic-design', '/services/seo', '/resources/freelance-proposal-template'],
  },
  {
    slug: 'freelance-proposal-template', path: '/resources/freelance-proposal-template', type: 'guide', keyword: 'freelance proposal template', skill: '', role: 'freelancer',
    title: 'Freelance Proposal Template: Scope, Milestones & Handover',
    description: 'Use this freelance proposal template to explain the client’s goal, deliverables, exclusions, milestones, fees and next steps before work begins.',
    intro: 'A useful freelance proposal connects the client’s problem to a specific scope of work. Use the copyable template below to make deliverables, assumptions and approval steps clear. Replace every placeholder and remove sections that do not apply.',
    example: ['Lead with the client’s goal, not your full biography.', 'Make scope and exclusions equally clear.', 'Give the client one specific next step.'],
    template: 'PROJECT PROPOSAL\nClient: [name] | Prepared by: [name] | Date: [date]\n\n1. Goal\nYou want to [outcome] for [audience]. This project will address [problem].\n\n2. Deliverables\nI will deliver [specific items, quantities and formats].\nCompletion means [reviewable acceptance criteria].\n\n3. Scope boundaries\nIncluded: [tasks and revision rounds].\nNot included: [exclusions and third-party costs].\n\n4. Inputs and timing\nYou will provide [assets/access/feedback] by [date].\nMilestone 1: [output and date].\nMilestone 2: [output and date].\nFinal handover: [files/access/instructions and date].\n\n5. Fees and payment\nProject fee: [amount and currency; clarify tax treatment].\nPayment stages: [amounts, triggers and due dates].\nAdditional work: [how changes will be estimated and approved].\n\n6. Communication and review\nUpdates: [channel and cadence].\nFeedback owner: [name]. Feedback window: [agreed period].\n\n7. Next step\nPlease confirm [scope/questions/decision] by [date].\nBefore starting, we will agree the applicable contract and payment arrangements.',
    sections: [
      { title: 'Personalise the opening', body: 'Restate the problem in the client’s own terms and explain what your work will change. Mention one relevant example of your experience if you have one. Avoid padding the proposal with unsupported success claims or a list of unrelated services. If a key part of the brief is unclear, ask a focused question rather than inventing an answer.' },
      { title: 'Make each deliverable reviewable', body: '“Social media design” is difficult to accept or reject. “Six editable square post templates and six exported examples using the supplied brand assets” is more concrete. Name quantities, formats and any variations. Describe how feedback rounds work, including whether a new direction after approval is a scope change.' },
      { title: 'Explain dependencies and payment stages', body: 'Tie the schedule to the inputs you actually need. If content must be approved before design begins, say so. Show payment triggers clearly and distinguish your fee from optional tools or third-party assets. Do not reuse sample figures as market prices; the template intentionally leaves amounts blank for your own estimate.' },
      { title: 'Review before sending', body: 'Check that names, dates, currency and deliverables are consistent. Remove placeholders and confirm that the next step is obvious. A proposal explains the offer; the contract and any platform terms determine the agreed working arrangements. Make sure those documents match the proposal before starting.', items: ['Does every promised outcome have a corresponding deliverable?', 'Are exclusions and client responsibilities easy to find?', 'Can the client understand what happens at each milestone?', 'Have you avoided promising results outside your control?'] },
    ],
    faq: [['How long should a freelance proposal be?', 'Long enough to make the decision and scope clear. A small project may only need a concise page; a complex project needs more detail. Avoid adding sections solely to make it look substantial.'], ['Can clients use this template too?', 'Yes. Clients can use its headings to check whether proposals cover the same scope and identify questions before accepting an offer.']],
    related: ['/resources/how-to-hire-a-freelancer', '/services/graphic-design', '/services/webdesign'],
  },
];

// Context links from existing pages into the recovered topic clusters.
for (const [path, index, target, label] of [["/services/webdesign",2,"/resources/building-portfolio-that-converts","What a useful portfolio case study shows"],["/services/graphic-design",1,"/resources/best-platform-designers","Compare channels for design work"],["/services/seo",1,"/resources/best-freelance-platforms-marketing-consultants","Choose a marketing consulting channel"],["/resources/freelance-proposal-template",3,"/resources/freelance-invoicing-guide","Prepare the invoice after approval"],["/resources/how-to-hire-a-freelancer",0,"/en/guides/platform-selectie/beste-freelance-platform-kiezen","Choose a platform for the project"]]) {
  seoPages.find(page => page.path === path).sections[index].links = [{ path: target, label }];
}
seoPages.push(...recoveryPages);

export const findSeoPage = (path) => seoPages.find((page) => page.path === path);
export function seoMetadata(page) {
  const base = process.env.NEXT_PUBLIC_SITE_URL || 'https://skilllinkup.com';
  const translations = page.translationKey ? seoPages.filter(p => p.translationKey === page.translationKey) : [];
  const languages = translations.length > 1 ? Object.fromEntries(translations.map(p => [p.locale || 'en', `${base}${p.path}`])) : undefined;
  return { title: page.title, description: page.description, alternates: { canonical: `${base}${page.path}`, languages }, openGraph: { title: page.title, description: page.description, url: `${base}${page.path}`, locale: page.locale === 'nl' ? 'nl_NL' : 'en_US', type: page.type === 'guide' ? 'article' : 'website', images: [{ url: `${base}/seo-og`, width: 1200, height: 630, alt: 'SkillLinkup — prepare your next freelance project' }] }, twitter: { card: 'summary_large_image', title: page.title, description: page.description, images: [`${base}/seo-og`] } };
}
